name: C1/CD app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app1:latest ./app1

      - name: docker hub login
        run: |
          echo ${{ secrets.DOCKER_PAT }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: push docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/app1:latest

      - name: deploy to ec2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SECRET }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/app1:latest 
            docker stop app1 || true
            docker rm app1 || true
            docker run -d \
            --name app1 \
            -p 3000:3000 \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/app1:latest
